### ISSUE TITLE
Хлеб

### ISSUE THREAD

**Issue by SavokBS** [BreadBSS/Modern-Brawl-v39#1]
ты млдц!

**Comment by SavokBS** [comment]
Только вот блять загрузить не загрузил хуеплет

**Comment by TheAcelot** [comment]
А савок бс тоже еблан

**Comment by BreadBSS** [comment]
@SavokBS ты че еблан
я не сюда ниче заливать

**Comment by TheAcelot** [comment]
А он только и умеет высирать хуйню

**Comment by StrikcYT** [comment]
> @SavokBS ты че еблан я сюда ниче не буду заливать

ДА ССЫЛКУ НА БРАВЛ КЛИЕНТ

**Comment by StrikcYT** [comment]
mgh
